[package]
name = "cocaine"
version = "0.2.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]
description = "Cocaine Framework Rust"
keywords = ["Cocaine"]
license = "MIT"

[dependencies]
log = "0.3"
rmp = { version = "0.8", path = "../rmp/rmp" }
rmp-serde = { version = "0.11", path = "../rmp/rmp-serde" }
rmpv = { version = "0.1", path = "../rmp/rmpv" }
serde = "0.8"
futures = "0.1"
tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }
slog = "1.4"
slog-term = "1.3"
slog-stdlog = "1.1"
slog-envlogger = "0.5"
